### PR TITLE
Convert to Postgres

### PR DESCRIPTION
**Pull request by tombeynon**

### CODE REVIEW

**Comment by tombeynon** [comment]
Wrong repo ❤️

**Comment by baktun14** [comment]
> Wrong repo ❤️

Hey Tom! You need help with something?

**Comment by tombeynon** [comment]
Hey man! All good, doing some internal analysis of Akash data and figured I wouldn't reinvent the wheel. Codebase is great, so far so good. I've converted it to PG and just testing out adding some more message handlers. 

Thanks for all your awesome work!

**Comment by baktun14** [comment]
Ok thanks! Are you planning to contribute to our codebase?

**Comment by tombeynon** [comment]
Definitely if I write anything of value 😂  Still working out the most appropriate tool to use, just been playing around so far.

**Comment by baktun14** [comment]
Ok sounds good!

**Pull request closed without merging**
